remote_theme: sharu725/online-cv
title: Dmitrii Baranov - Staff Back-End Engineer (PHP, Go) - CV
url: 'https://baranov.in/'
description: |
  Personal Web CV of Dmitrii Baranov - Staff Back-End Engineer (PHP, Go).
  I have a huge experience developing complex PHP applications using Symfony framework.
  Key skills: PHP, Go, Symfony, MySQL, PostgreSQL, ElasticSearch, RabbitMQ, Redis, Docker,
  Linux, Networks.
theme_skin: ceramic

sass:
  sass_dir: _sass
  style: compressed

compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development
